import {Injector} from '@angular/core';
import {SdsSecurityService} from '@sdv/sdv-core';
import {SecurityContext} from '@set-social-services/common-core';
import {DtLoginCredential, DtTagConfigService} from '../services/dt-tag-config.service';

// TODO: Import required only to work with a locally logged in user.

/**
 * @author Bruno Ramirez
 */
export class DtLocalLoginTest {
  private _securityContext: SecurityContext;
  private _sdsSecurityService: SdsSecurityService;
  private _dtTagConfigService: DtTagConfigService;

  private readonly _USER = {
    userId: 'NZYzpm5w',
    token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOWll6cG01dyIsInVzZXJfZW1haWwiOiJicmFtaXJlekBnbWFpbC5jb20iLCJ1c2VyX25hbWUiOiJicmFtaXJleiIsImxhc3RfbmFtZSI6InJhbWlyZXoiLCJsYXN0X3N1Y2Nlc3NmdWxfbG9naW4iOjE3NDEyNjk3MDcwMDAsInVzZXJfcm9sZXMiOlt7ImlkIjo2LCJuYW1lIjoiRGV2ZWxvcGVyIiwidWlkIjoiZGV2LXJvbGUifV0sImNsaWVudF9pZCI6InNldF9zb2NpYWxzZXJ2aWNlcyIsInN1YnNjcmlwdGlvbl9pZCI6ImR0ZGUiLCJhdWQiOlsiRGlnaXRhbEhhcmJvciJdLCJpZHAiOiIiLCJ1c2VyX2lkIjoiTlpZenBtNXciLCJzY29wZSI6WyJ3cml0ZSJdLCJhY3RpdmVfcm9sZSI6eyJpZCI6NiwibmFtZSI6IkRldmVsb3BlciIsInVpZCI6ImRldi1yb2xlIn0sImRlcGFydG1lbnRzIjpbXSwiZXhwIjoxNzQxMzU2MTA3LCJmaXJzdF9uYW1lIjoiYnJ1bm8iLCJqdGkiOiJNVGJ4RVJZS2RCYl91Q1k4MDF5N0d1M25ia2cifQ.tPAfJJEhc7GvlpVNubtkIjdjdFX_5UB8_NZURZu9k4suPQIFxKAd3j4xgqdnOK_uPmGFIW6aDpIPoU3myDSYoWzpNYl4lkd2zhVKJscQ7yLVOgDC2_g6BfmsgQ_RzuucJAQdP5lgg5pdr13JpefNUBBZL9qM6U5L39anASiCKd8cobc3WP4GqsqSYH5fKoz2_VzoRMJStEGn2vKKCvPHiFLY6XkvuJ8mfeXlIdHuD9yDOt3PyovDBlK3u294OYi1-pd9KteYfWRwnSE2KldnCnjSw4rP3zN0VsXejngJF3rCJAK0lttdWkmXe6nLkHhUkF2AUXwQ7lsrfjSj0LbHqA',
    accessToken: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOWll6cG01dyIsInVzZXJfZW1haWwiOiJicmFtaXJlekBnbWFpbC5jb20iLCJ1c2VyX25hbWUiOiJicmFtaXJleiIsImxhc3RfbmFtZSI6InJhbWlyZXoiLCJsYXN0X3N1Y2Nlc3NmdWxfbG9naW4iOjE3NDEyNjk3MDcwMDAsInVzZXJfcm9sZXMiOlt7ImlkIjo2LCJuYW1lIjoiRGV2ZWxvcGVyIiwidWlkIjoiZGV2LXJvbGUifV0sImNsaWVudF9pZCI6InNldF9zb2NpYWxzZXJ2aWNlcyIsInN1YnNjcmlwdGlvbl9pZCI6ImR0ZGUiLCJhdWQiOlsiRGlnaXRhbEhhcmJvciJdLCJpZHAiOiIiLCJ1c2VyX2lkIjoiTlpZenBtNXciLCJzY29wZSI6WyJ3cml0ZSJdLCJhY3RpdmVfcm9sZSI6eyJpZCI6NiwibmFtZSI6IkRldmVsb3BlciIsInVpZCI6ImRldi1yb2xlIn0sImRlcGFydG1lbnRzIjpbXSwiZXhwIjoxNzQxMzU2MTA3LCJmaXJzdF9uYW1lIjoiYnJ1bm8iLCJqdGkiOiJNVGJ4RVJZS2RCYl91Q1k4MDF5N0d1M25ia2cifQ.tPAfJJEhc7GvlpVNubtkIjdjdFX_5UB8_NZURZu9k4suPQIFxKAd3j4xgqdnOK_uPmGFIW6aDpIPoU3myDSYoWzpNYl4lkd2zhVKJscQ7yLVOgDC2_g6BfmsgQ_RzuucJAQdP5lgg5pdr13JpefNUBBZL9qM6U5L39anASiCKd8cobc3WP4GqsqSYH5fKoz2_VzoRMJStEGn2vKKCvPHiFLY6XkvuJ8mfeXlIdHuD9yDOt3PyovDBlK3u294OYi1-pd9KteYfWRwnSE2KldnCnjSw4rP3zN0VsXejngJF3rCJAK0lttdWkmXe6nLkHhUkF2AUXwQ7lsrfjSj0LbHqA',
    tenantId: 'dtde',
    rol: 'Developer',
    userName: 'bramirez',
    firstName: 'bruno',
    lastName: 'ramirez',
    fingerPrint: 'fingerprintTest',
    refreshToken: ''
  };

  private readonly _USER_QA = {
    userId: '7CMMGHjk',
    token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Q01NR0hqayIsInVzZXJfZW1haWwiOiJicnVuby5yYW1pcmV6QGRoYXJib3IuY29tIiwidXNlcl9uYW1lIjoiYnJ1bm9yYW1pcmV6IiwibGFzdF9uYW1lIjoiUmFtaXJleiIsImxhc3Rfc3VjY2Vzc2Z1bF9sb2dpbiI6MTc0MTMzNjUxNzExNiwidXNlcl9yb2xlcyI6W3siaWQiOjIzLCJuYW1lIjoiaWRwX2RvdC1zc28tbXNfdXNlciIsInVpZCI6ImlkcF9kb3Qtc3NvLW1zX3VzZXIiLCJhbGlhcyI6ImlkcF9kb3Qtc3NvLW1zX3VzZXIifV0sImNsaWVudF9pZCI6ImRvdCIsInN1YnNjcmlwdGlvbl9pZCI6ImRvdHEiLCJhdWQiOlsiRGlnaXRhbEhhcmJvciJdLCJpZHAiOiJkb3Qtc3NvLW1zIiwidXNlcl9pZCI6IjdDTU1HSGprIiwic2NvcGUiOlsid3JpdGUiXSwiYWN0aXZlX3JvbGUiOnsiaWQiOjIzLCJuYW1lIjoiaWRwX2RvdC1zc28tbXNfdXNlciIsInVpZCI6ImlkcF9kb3Qtc3NvLW1zX3VzZXIiLCJhbGlhcyI6ImlkcF9kb3Qtc3NvLW1zX3VzZXIifSwiZGVwYXJ0bWVudHMiOltdLCJleHAiOjE3NDE0MjI5MTcsImZpcnN0X25hbWUiOiJCcnVubyIsImp0aSI6IlNLTzlSUDQ2VXcyVWVOSHltS1ZnaWRYMW9fVSJ9.uIWb6JIMaI7YjteHzVyfB1Ulm9T_EMXvz3qXAICTEKKWXXGqG41wFiJ3pygZ_wZpy499EDig84tJSSingZ8TPHfA1eka5OMqSWIY6EpvY-OTputoN8lnKV8ZA-AzxQ39Iu-rTrPFz6uU474Qi24w2zZRmnZBrx1k7GbaSRJ-47OxHUcZ6Y4f0bmi8ZhbJ3pLwDHQGCFgfKI6ZOUgFDG-yXmDpfMKb5LdR5dEcGYRs4ZI9ehzEHh1tD5XW52ti-Q0UoXTislwZ9jKyG7o9R95SIVxBL3QBLxRV1c4HfWp5e5Pv0CNtEJKLDgtXZjwQBc7VGRa-ycjwIJyD415Nbeduw',
    accessToken: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Q01NR0hqayIsInVzZXJfZW1haWwiOiJicnVuby5yYW1pcmV6QGRoYXJib3IuY29tIiwidXNlcl9uYW1lIjoiYnJ1bm9yYW1pcmV6IiwibGFzdF9uYW1lIjoiUmFtaXJleiIsImxhc3Rfc3VjY2Vzc2Z1bF9sb2dpbiI6MTc0MTMzNjUxNzExNiwidXNlcl9yb2xlcyI6W3siaWQiOjIzLCJuYW1lIjoiaWRwX2RvdC1zc28tbXNfdXNlciIsInVpZCI6ImlkcF9kb3Qtc3NvLW1zX3VzZXIiLCJhbGlhcyI6ImlkcF9kb3Qtc3NvLW1zX3VzZXIifV0sImNsaWVudF9pZCI6ImRvdCIsInN1YnNjcmlwdGlvbl9pZCI6ImRvdHEiLCJhdWQiOlsiRGlnaXRhbEhhcmJvciJdLCJpZHAiOiJkb3Qtc3NvLW1zIiwidXNlcl9pZCI6IjdDTU1HSGprIiwic2NvcGUiOlsid3JpdGUiXSwiYWN0aXZlX3JvbGUiOnsiaWQiOjIzLCJuYW1lIjoiaWRwX2RvdC1zc28tbXNfdXNlciIsInVpZCI6ImlkcF9kb3Qtc3NvLW1zX3VzZXIiLCJhbGlhcyI6ImlkcF9kb3Qtc3NvLW1zX3VzZXIifSwiZGVwYXJ0bWVudHMiOltdLCJleHAiOjE3NDE0MjI5MTcsImZpcnN0X25hbWUiOiJCcnVubyIsImp0aSI6IlNLTzlSUDQ2VXcyVWVOSHltS1ZnaWRYMW9fVSJ9.uIWb6JIMaI7YjteHzVyfB1Ulm9T_EMXvz3qXAICTEKKWXXGqG41wFiJ3pygZ_wZpy499EDig84tJSSingZ8TPHfA1eka5OMqSWIY6EpvY-OTputoN8lnKV8ZA-AzxQ39Iu-rTrPFz6uU474Qi24w2zZRmnZBrx1k7GbaSRJ-47OxHUcZ6Y4f0bmi8ZhbJ3pLwDHQGCFgfKI6ZOUgFDG-yXmDpfMKb5LdR5dEcGYRs4ZI9ehzEHh1tD5XW52ti-Q0UoXTislwZ9jKyG7o9R95SIVxBL3QBLxRV1c4HfWp5e5Pv0CNtEJKLDgtXZjwQBc7VGRa-ycjwIJyD415Nbeduw',
    tenantId: 'dotq',
    rol: 'idp_dot-sso-ms_user',
    userName: 'brunoramirez',
    firstName: 'bruno',
    lastName: 'ramirez',
    fingerPrint: 'fingerprintTest',
    refreshToken: ''
  };

  constructor(private _injector: Injector) {
    this._securityContext = this._injector.get(SecurityContext);
    this._sdsSecurityService = this._injector.get(SdsSecurityService);
    this._dtTagConfigService = this._injector.get(DtTagConfigService);
  }

  public initSession(): void {
    sessionStorage.setItem('DD_USER_ID', this._USER.userId);
    this._sdsSecurityService.sdsSessionService().setUserLogged(this._USER.userId, this._USER.token, this._USER.tenantId, this._USER.rol);
    this._securityContext.sessionService().setUserLogged(this._USER.userId, this._USER.token, this._USER.tenantId, this._USER.rol);
    this._initTagsSession(this._USER);
  }

  private _initTagsSession(userCredential: DtLoginCredential): void {
    this._dtTagConfigService.initializeTagConfig(userCredential);
  }
}
