export enum DtAction {
  CREATE_IFRAME = 'CREATE_IFRAME',
  DELETE_IFRAME = 'DELETE_IFRAME',
  CHANGE_WINDOW_BOUNDS = 'CHANGE_WINDOW_BOUNDS',
  INIT_TAKE_SCREENSHOT = 'INIT_TAKE_SCREENSHOT',
  INIT_SEE_SOMETHING = 'INIT_SEE_SOMETHING',
  SET_IGNORE_MOUSE_EVENTS = 'SET_IGNORE_MOUSE_EVENTS',
  SET_FULL_SCREEN = 'SET_FULL_SCREEN',
  BUILD_BROWSER_WINDOW = 'BUILD_BROWSER_WINDOW',
  LISTEN_TO_SCREENSHOT_TAKEN = 'LISTEN_TO_SCREENSHOT_TAKEN',
}
